version: '3.8'

services:
  # NGINX, который будет служить фронтенд-сервером и проксировать запросы к серверу Node.js
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Открываем порт 80 для доступа извне
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Подключаем кастомную конфигурацию NGINX
    networks:
      - my-todos-network

  # Клиентское приложение (React.js)
  client:
    image: andrey522526/my-todos-app:client-v3  # Образ клиента из Docker Hub
    expose:
      - "80"  # Порт, на котором клиент доступен внутри Docker-сети
    networks:
      - my-todos-network

  # Сервер Node.js
  server:
    image: andrey522526/my-todos-app:servvv  # Образ сервера из Docker Hub
    expose:
      - "8082"  # Порт, по которому сервер будет доступен внутри Docker-сети
    environment:
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: rlDEB2V7QCdX
      POSTGRES_DB: todos
      DATABASE_URL: postgres://koyeb-adm:rlDEB2V7QCdX@ep-damp-wave-a22ezu5j.eu-central-1.pg.koyeb.app/todos
    networks:
      - my-todos-network

networks:
  my-todos-network:
