version: '3.8'

# Определение пользовательской сети
networks:
  my-todos-network:
    driver: bridge 

services:
  # Сервер Node.js
  server:
    image: andrey522526/my-todos-app:server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      DATABASE_URL: postgres://postgres:andrey@db:5432/todos
    depends_on:
      - db
    networks:
      - my-todos-network

  # Клиент (React.js)
  client:
    image: andrey522526/my-todos-app:client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - my-todos-network

  # База данных PostgreSQL
  db:
    image: andrey522526/my-todos-app:db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - todos-db:/var/lib/postgresql/data
    networks:
      - my-todos-network

volumes:
  todos-db:
