version: '3.8'

services:
  # Сервер Node.js
  server:
    image: andrey522526/my-todos-app:server
    ports:
      - "8082:8082"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      DATABASE_URL: postgres://postgres:andrey@db:5432/todos
    depends_on:
      - db

  # Клиент (React.js)
  client:
    image: andrey522526/my-todos-app:client
    ports:
      - "80:80"
    depends_on:
      - server

  # База данных PostgreSQL
  db:
    image: andrey522526/my-todos-app:db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg_backup.sql

# Определение тома для хранения данных PostgreSQL
volumes:
  todos-db-1:
